### PR TITLE
Fix bug to prevent /ec when editing doctor

### LINKED ISSUE #221: Inconsistency bug in EditCommand
Discovered a bug in EditCommand where entering a valid emergency contact with the ec/ prefix for Doctors will result in a successfully edited message. This is different from when entering blood type and condition prefixes, where the appropriate error message will be shown.

input entered: edit s9851306G ec/999

image

### PR DESCRIPTION
**Pull request by tanveersingh10**
fixes #221

### CODE REVIEW

**Review by cmHuang777 — APPROVED** [review]
Looks great. May be you can also try to cover the test cases for the newly added code.

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -125,31 +125,40 @@ private Person getPersonToEdit(Model model) throws CommandException {
...
+                || editPersonDescriptor.getEmergencyContact().isPresent()) {
+            logger.warning("Error thrown - tried to edit condition/blood type/emergency contact of doctor");
+            throw new CommandException("Doctors cannot have Condition, BloodType or Emergency Contact fields.");
+        }
+        if (editPersonDescriptor.getTags().isPresent()
+                && !editPersonDescriptor.isValidDoctorTagList(editPersonDescriptor.getTags().get())) {
+            logger.warning(editPersonDescriptor.getTags().toString());
+            throw new CommandException("Please enter valid Doctor tags.");
+        }
+    }
```
Comment (chonguschonguschongus) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:161]: gotta write new test cases for all these!

**Review by chonguschonguschongus — APPROVED** [review]
LGTM. Good job on solving the issue, now just to ensure code coverage is good!
